services:
  gluetun-qbittorrent-port-bind:
    image: mhabes/gluetun-qbittorrent-port-bind:latest
    container_name: gluetun-qbittorrent-port-bind
    network_mode: "container:gluetun"
    environment:
      - GLUETUN_SERVER=localhost
      - GLUETUN_PORT=8000
      - QBITTORRENT_SERVER=localhost
      - QBITTORRENT_PORT=8080
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_PASSWORD=adminadmin
    restart: unless-stopped
